---
title: "Appendix A: Normality & Random Walk 1 & 3"


output:
  html_document: default
  word_document: default
  pdf_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
	message = FALSE,
	warning = FALSE,
	show_col_types = FALSE)

pacman::p_load(
  fixest,
  modelsummary,
  margins,
  wooldridge,
  AER,
  janitor,
  kableExtra,
  tidyverse,
  haven,
  patchwork,
  hdm,
  randomForest,
  ranger,
  glmnet,
  matrixStats,
  scales, 
  forcats,
  patchwork,
  lmtest, 
  insight,
  stargazer
)

# Set the graphical theme
ggplot2::theme_set(ggplot2::theme_light())
```

```{r}
#Glob
csv_files_D <- list.files(path = "C:/Users/AHM/OneDrive/York MA/5520 Econ of Financial Markets/Term Project/Data", pattern = "*D.csv")

csv_files_M <- list.files(path = "C:/Users/AHM/OneDrive/York MA/5520 Econ of Financial Markets/Term Project/Data", pattern = "*M.csv")
```

```{r}
#Add_return function
 Add_return <- function (.data){
   .data <- .data %>%
     mutate(
       Adj_close_lagged = lag (Adj_close),
       returns =  Adj_close/Adj_close_lagged
       )
 }
```

```{r results='asis'} 
######################For Daily Frequency
df <- data.frame()
sig_lags_D <-  data.frame(Criteria = "Pearson's AutoCorrelation Coefficients")
sig_lags_D_2 <-  data.frame(Criteria = "Portmanteau Statistics")
sig_lags_D_3 <-  data.frame(Criteria = "Variance Ratio")
mlist <- list()
forecast_model <- data.frame("Last Lag to be included" = rep(NA, 62))
n <- 1

# Loop over file names, read each file into a data frame and do some wrangling

for (file in csv_files_D) {
  
  # Read the file into a data frame
  file_data <- read.csv(file.path("C:/Users/AHM/OneDrive/York MA/5520 Econ of Financial Markets/Term Project/Data", file))
  
  #Rename the adj close column
  colnames(file_data)[6] = "Adj_close"
  
  #add returns column
  file_data <- Add_return(file_data)
  
  #drop all columns except returns
  file_data <- select(file_data, returns)
  
  #Add log returns
  file_data["log_returns"] <- log(file_data$returns)
  
   #Drop NA
  file_data <- na.omit(file_data)
  
  rt_bar <- mean(file_data$log_returns)
  
  #Add lags
  for (i in 1:10) {
  file_data[, paste0("lag", i)] <- lag(file_data$log_returns, i)
  file_data[, paste0("numerator_", i)]  <- ((file_data$log_returns-rt_bar)^2)*((file_data[,paste0("lag", i)] - rt_bar)^2)
  }
  
  file_data <- file_data %>% mutate(denominator = (log_returns - rt_bar)^2)

  
  cat("<h1> ", gsub(".csv", "", file), "</h1>\n")
  cat("\n", "<h2><b>Checking for Normality</b></h2>","\n")

  
  ####################Normality######################
  library(tseries)
  jb_stat <-  jarque.bera.test(file_data$log_returns)$statistic
  cat("\n", "Jarque-Bera Statistic: ", jb_stat, "\n")
  
  if(abs(jb_stat) > 1.96) {
    output <- sprintf('<p style="background-color:yellow">Returns are not Normally Distributed</p>')
  } else {
    output <- sprintf('<p style="background-color:yellow">Returns are Normally Distributed</p>')
  }
  cat(output)
  
  ################Pearson Autocorrelation############
  Model <- lm (log_returns ~ lag1 + lag2 + lag3 + lag4 + lag5 + lag6 + lag7 + lag8 + lag9 + lag10, data=file_data)
  mlist[[paste0("model_", gsub(".csv", "", file))]] <- Model
  ct_list <- lapply(mlist, coeftest)
  last_element <- ct_list[[length(ct_list)]]
  cat("\n", "<h2><b>Checking for Random Walk 1</b></h2>","\n")
  cat("\n","Regressing Log Returns on its 10 lags", "\n")
  stargazer(last_element, type="html", header=FALSE, nobs = F, mean.sd = F, min.max = F) 
  
  
  coef_table <- summary(Model)$coefficients
  assign(paste0(gsub(".csv", "", file)," ACFs"), coef_table)
  coef_table <- coef_table[-1,]
  
  #####Autocorrelation Coefficients
  #Check which lags are significant
  df  <- rbind(df, rownames(coef_table)[coef_table[, 4] < 0.05])
  #Check if there is random walk i.e. if none of the lags are significant
  if (nrow(df) == 0) {
    df <-  data.frame(combined = "Random Walk 1") 
  } else {
    df$combined<- apply(df, 1, function(x) paste(x, collapse = " "))
  }
  # Get the name of the current file
  
  sig_lags_D <-  cbind(sig_lags_D, df$combined) 
  colnames(sig_lags_D)[ncol(sig_lags_D)] <-  gsub(".csv", "", file)
  
  
  
  ####Portmanteau Stat
  df2  <- data.frame(Coefficients = coef_table[,1])
  df2 <- df2 %>% mutate (Coefficients_sq = Coefficients^2)
  
  Q <- data.frame()
  for (i in 1:10) {
    Q <- rbind(Q, sum(head(df2$Coefficients_sq, i))*2507)
    rownames(Q)[nrow(Q)] <- paste0("lag", i)
  }
  df2 <- cbind (df2, Q)
  colnames(df2)[3] <- "P_stat"
  
  df2 <- df2 %>% mutate (chi_stat = c(qchisq(0.95, 1),qchisq(0.95, 2), qchisq(0.95, 3), qchisq(0.95, 4), qchisq(0.95, 5), qchisq(0.95, 6), qchisq(0.95, 7),qchisq(0.95, 8), qchisq(0.95, 9), qchisq(0.95, 10)), sig = ifelse (P_stat>chi_stat, 1,0), Q = ifelse(P_stat > chi_stat, paste0(P_stat, "*"), P_stat))
  
  assign(paste0(gsub(".csv", "", file), " P_Stat"), df2)
  
  cat("\n","\n", "Portmanteau Statisitics for 10 lags", "\n")
  
  df4 <- df2[df2$sig == 1,]
  
  df2 <- select(df2, Q)
  print(knitr::kable(df2,
             escape = F,
             longtable = F)  %>%
  kable_classic_2())
  
 
  df3 <- data.frame()
  df3<- rbind(df3,row.names(df4))
 
   if (nrow(df3) == 0) {
    df3 <-  data.frame(combined = "Random Walk 1") 
    output <- sprintf('<p style="background-color:yellow">Returns are Random Walk 1</p>')
  } else {
    df3$combined<- apply(df3, 1, function(x) paste(x, collapse = " "))
    output <- sprintf('<p style="background-color:yellow">Returns are not Random Walk 1</p>')
  }
  cat(output)
  
  sig_lags_D_2 <-  cbind(sig_lags_D_2, df3$combined)
  colnames(sig_lags_D_2)[ncol(sig_lags_D_2)] <-  gsub(".csv", "", file)
 
  #RW3
  rw_3 <- data.frame(row_k = rep(NA, 10), delta_k = rep(NA, 10), q = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11), VR_q = rep(NA, 10), Theta_q = rep(NA, 10), Psi_q = rep(NA,10))
  
  for (k in 1:10){
    rw_3[k,1] <- coef_table[(k),1]
    rw_3[k,2] <- 2517 * (sum(file_data[,paste0("numerator_", k)], na.rm = T)) / (sum(file_data$denominator, na.rm = T)^2)
  }
  
  for (q in 2:11){
    result_th <- 0
    result_vr <- 0
  
    for (k in 1:(q-1)) {
      result_th <- result_th + (rw_3[k,2] * ((2 * (1 - k/q))^2))
      result_vr <- result_vr + (rw_3[k,1] * (2 * (1 - k/q)))
  
    }
    rw_3[q-1,5] <- result_th
    rw_3[q-1, 4] <- 1 + result_vr
    rw_3[q-1,6] <- (sqrt(2517) * (result_vr))/sqrt(result_th)
  }
  
  df_rw3 <- rw_3 %>% mutate(
    sig = ifelse (abs(Psi_q)>1.96, 1,0)
    )
  
  rw_3 <- rw_3 %>% mutate(
    Psi_q = ifelse(abs(Psi_q) > 1.96, paste0(Psi_q, "*"), Psi_q)
    )
  
  
  
  df6 <- df_rw3[df_rw3$sig == 1,]
  
  cat("\n", "<h2><b>Checking for Random Walk 3</b></h2>","\n")
  
  print(knitr::kable(rw_3,
             escape = F,
             longtable = T,
             row.names = TRUE)  %>%
  kable_classic_2())
  
  df7 <- data.frame()

  df7<- rbind(df7,rownames(df6))
  
  if (nrow(df7) == 0) {
    df7 <-  data.frame(combined = "Random Walk 3") 
    output <- sprintf('<p style="background-color:yellow">Returns are Random Walk 3</p>')
    forecast_model[n,1] <- "0 (Random Walk)"
  } else {
    df7$combined<- apply(df7, 1, function(x) paste(x, collapse = " "))
    output <- sprintf('<p style="background-color:yellow">Returns are not Random Walk 3</p>')
    x_list <- strsplit(df$combined, " ")[[1]]
    last_char <- tail(x_list, 1)
    forecast_model[n,1] <- last_char
  }
  cat(output)
  
  sig_lags_D_3 <-  cbind(sig_lags_D_3, df7$combined)
  colnames(sig_lags_D_3)[ncol(sig_lags_D_3)] <-  gsub(".csv", "", file)
  
  assign(paste0(gsub(".csv", "", file), " RW3"), rw_3)
  
  df2 <- data.frame()
  df3 <- data.frame()
 
  # Assign the data frame to a variable based on the file name
  assign(gsub(".csv", "", file), file_data)
  
  cat("<hr style='border-top: 1px dashed #aaa;'>")
  cat("<hr style='border-top: 1px dashed #aaa;'>")
  cat("<hr style='border-top: 1px dashed #aaa;'>")
  
  rownames(forecast_model)[n] <-  gsub(".csv", "", file)
  
  df <- data.frame()
  n <- n+1
}

sig_lags_D <- t(sig_lags_D)
sig_lags_D_2 <- t(sig_lags_D_2)
sig_lags_D_3 <- t(sig_lags_D_3)

sig_lags_Daily <- cbind (sig_lags_D, sig_lags_D_2, sig_lags_D_3)

colnames(sig_lags_Daily) <- sig_lags_Daily[1,]

# Remove the first row
sig_lags_Daily <- sig_lags_Daily[-1,]


```

``` {r results='asis'}
##########################For Monthly Frequency
sig_lags_M <-  data.frame(Criteria = "Pearson AutoCorrelation Coefficients")
sig_lags_M_2 <-  data.frame(Criteria = "Portmanteau Statistics")
sig_lags_M_3 <-  data.frame(Criteria = "Variance Ratio")

# Loop over file names, read each file into a data frame and do some wrangling

for (file in csv_files_M) {
  
  # Read the file into a data frame
  file_data <- read.csv(file.path("C:/Users/AHM/OneDrive/York MA/5520 Econ of Financial Markets/Term Project/Data", file))
  
  #Rename the adj close column
  colnames(file_data)[6] = "Adj_close"
  
  #add returns column
  file_data <- Add_return(file_data)
  
  #drop all columns except returns
  file_data <- select(file_data, returns)
  
  #Add log returns
  file_data["log_returns"] <- log(file_data$returns)
  
  #Drop NA
  file_data <- na.omit(file_data)
  
  rt_bar <- mean(file_data$log_returns)
  
  #Add lags
  for (i in 1:5) {
  file_data[, paste0("lag", i)] <- lag(file_data$log_returns, i)
  file_data[, paste0("numerator_", i)]  <- ((file_data$log_returns-rt_bar)^2)*((file_data[,paste0("lag", i)] - rt_bar)^2)
  }
  
  file_data <- file_data %>% mutate(denominator = (log_returns - rt_bar)^2)
  
  cat("<h1> ", gsub(".csv", "", file), "</h1>\n")
  cat("\n", "<h2><b>Checking for Normality</b></h2>","\n")
  
  ####################Normality######################
  library(tseries)
  jb_stat <-  jarque.bera.test(file_data$returns - 1)$statistic
  cat("\n", "Jarque-Bera Statistic: ", jb_stat, "\n")
  
  if(abs(jb_stat) > 1.96) {
    output <- sprintf('<p style="background-color:yellow">Returns are not Normally Distributed</p>')
  } else {
    output <- sprintf('<p style="background-color:yellow">Returns are Normally Distributed</p>')
  }
  cat(output)

  
  ################Pearson Autocorrelation############
  Model <- lm (log_returns ~ lag1 + lag2 + lag3 + lag4 + lag5, data=file_data)
  mlist[[paste0("model_", gsub(".csv", "", file))]] <- Model
  ct_list <- lapply(mlist, coeftest)
  last_element <- ct_list[[length(ct_list)]]
  cat("\n", "<h2><b>Checking for Random Walk 1</b></h2>","\n")
  cat("\n","Regressing Log Returns on its 5 lags", "\n")
  stargazer(last_element, type="html", header=FALSE, nobs = F, mean.sd = F, min.max = F)
  
  
  coef_table <- summary(Model)$coefficients
  
  assign(paste0(gsub(".csv", "", file)," ACFs"), coef_table)
  coef_table <- coef_table[-1,]
  
  
  #####Autocorrelation Coefficients
  #Check which lags are significant
  df  <- rbind(df, rownames(coef_table)[coef_table[, 4] < 0.05])
  #Check if there is random walk i.e. if none of the lags are significant
  if (nrow(df) == 0) {
    df <-  data.frame(combined = "Random Walk 1")
  } else {
    df$combined<- apply(df, 1, function(x) paste(x, collapse = " "))
  }
  # Get the name of the current file
  file_name <- basename(file)
  sig_lags_M <-  cbind(sig_lags_M, df$combined) 
  colnames(sig_lags_M)[ncol(sig_lags_M)] <-  gsub(".csv", "", file)
  
  
  
  ####Portmanteau Stat
  df2  <- data.frame(Coefficients = coef_table[,1])
  df2 <- df2 %>% mutate (Coefficients_sq = Coefficients^2)
  
  Q <- data.frame()
  for (i in 1:5) {
    Q <- rbind(Q, sum(head(df2$Coefficients_sq, i))*114)
    rownames(Q)[nrow(Q)] <- paste0("lag", i)
  }
  df2 <- cbind (df2, Q)
  
  colnames(df2)[3] <- "P_stat"
  
  df2 <- df2 %>% mutate (chi_stat = c(qchisq(0.95, 1),qchisq(0.95, 2), qchisq(0.95, 3), qchisq(0.95, 4), qchisq(0.95, 5)), sig = ifelse (P_stat>chi_stat, 1,0),  Q = ifelse(P_stat > chi_stat, paste0(P_stat, "*"), P_stat))
  cat("\n", "Portmanteau Statisitics for 5 lags", "\n")
  df4 <- df2[df2$sig == 1,]
  
  df2 <- select(df2,Q)

  print(knitr::kable(df2,
             escape = F,
             longtable = F)  %>%
  kable_classic_2())
  
  assign(paste0(gsub(".csv", "", file), " P_Stat"), df2)
  
 
  df3 <- data.frame()
  df3<- rbind(df3,rownames(df4))
 
  if (nrow(df3) == 0) {
    df3 <-  data.frame(combined = "Random Walk 1") 
    output <- sprintf('<p style="background-color:yellow">Returns are Random Walk 1</p>')
  } else {
    df3$combined<- apply(df3, 1, function(x) paste(x, collapse = " "))
    output <- sprintf('<p style="background-color:yellow">Returns are not Random Walk 1</p>')
  }
  cat(output)
  
  sig_lags_M_2 <-  cbind(sig_lags_M_2, df3$combined)
  colnames(sig_lags_M_2)[ncol(sig_lags_M_2)] <-  gsub(".csv", "", file)
 
  #RW3
  rw_3 <- data.frame(row_k = rep(NA, 5), delta_k = rep(NA, 5), q = c(2, 3, 4, 5, 6), VR_q = rep(NA, 5), Theta_q = rep(NA, 5), Psi_q = rep(NA,5))
  
  for (k in 1:5){
    rw_3[k,1] <- coef_table[(k),1]
    rw_3[k,2] <- 114 * (sum(file_data[,paste0("numerator_", k)], na.rm = T)) / (sum(file_data$denominator, na.rm = T)^2)
  }
  
  for (q in 2:6){
    result_th <- 0
    result_vr <- 0
  
    for (k in 1:(q-1)) {
      result_th <- result_th + (rw_3[k,2] * ((2 * (1 - k/q))^2))
      result_vr <- result_vr + (rw_3[k,1] * (2 * (1 - k/q)))
  
    }
    rw_3[q-1,5] <- result_th
    rw_3[q-1, 4] <- 1 + result_vr
    rw_3[q-1,6] <- (sqrt(114) * (result_vr))/sqrt(result_th)
  }
  
  df_rw3 <- rw_3 %>% mutate(
    sig = ifelse (abs(Psi_q)>1.96, 1,0)
    )
  
  rw_3 <- rw_3 %>% mutate(
    Psi_q = ifelse(abs(Psi_q) > 1.96, paste0(Psi_q, "*"), Psi_q)
    )
  
  df6 <- df_rw3[df_rw3$sig == 1,]
  
  cat("\n", "<h2><b>Checking for Random Walk 3</b></h2>","\n")
  
  print(knitr::kable(rw_3,
             escape = F,
             longtable = T,
             row.names = TRUE)  %>%
  kable_classic_2())
  
  df7 <- data.frame()
  
  df7<- rbind(df7,rownames(df6))
  
  if (nrow(df7) == 0) {
    df7 <-  data.frame(combined = "Random Walk 3") 
    output <- sprintf('<p style="background-color:yellow">Returns are Random Walk 3</p>')
    forecast_model[n,1] <- "0 (Random Walk)"
  } else {
    df7$combined<- apply(df7, 1, function(x) paste(x, collapse = " "))
    output <- sprintf('<p style="background-color:yellow">Returns are not Random Walk 3</p>')
    x_list <- strsplit(df$combined, " ")[[1]]
    last_char <- tail(x_list, 1)
    forecast_model[n,1] <- last_char
  }
  cat(output)
  
  sig_lags_M_3 <-  cbind(sig_lags_M_3, df7$combined)
  colnames(sig_lags_M_3)[ncol(sig_lags_M_3)] <-  gsub(".csv", "", file)
  
  
  
  assign(paste0(gsub(".csv", "", file), " RW3"), rw_3)
  
  df2 <- data.frame()
  df3 <- data.frame()
 
  # Assign the data frame to a variable based on the file name
  assign(gsub(".csv", "", file), file_data)
  
  cat("<hr style='border-top: 1px dashed #aaa;'>")
  cat("<hr style='border-top: 1px dashed #aaa;'>")
  cat("<hr style='border-top: 1px dashed #aaa;'>")
  
  rownames(forecast_model)[n] <-  gsub(".csv", "", file)
  
  df <- data.frame()
  n <- n+1
}

sig_lags_M <- t(sig_lags_M)
sig_lags_M_2 <- t(sig_lags_M_2)
sig_lags_M_3 <- t(sig_lags_M_3)

sig_lags_Monthly <- cbind (sig_lags_M, sig_lags_M_2, sig_lags_M_3)

colnames(sig_lags_Monthly) <- sig_lags_Monthly[1,]

# Remove the first row
sig_lags_Monthly <- sig_lags_Monthly[-1,]



Model_Lags <- rbind (sig_lags_Daily, sig_lags_Monthly)

Model_Lags <- cbind(Model_Lags, forecast_model)


```
##Summary of results
```{r}


knitr::kable(Model_Lags,
             escape = F,
             longtable = T)  %>%
             add_header_above(c(" " = 1, "Checking for Random Walk 1 " = 2, "Checking for Random Walk 3 " = 1, "Forecast Model")) %>%
  kable_classic_2()


```
