---
title: "Stochastic Dominance"
author: "Ali"
date: "2023-01-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
	message = FALSE,
	warning = FALSE,
	show_col_types = FALSE)

pacman::p_load(
  fixest,
  modelsummary,
  margins,
  wooldridge,
  AER,
  janitor,
  kableExtra,
  tidyverse,
  haven,
  patchwork,
  hdm,
  randomForest,
  ranger,
  glmnet,
  matrixStats,
  scales, 
  forcats,
  patchwork
)

# Set the graphical theme
ggplot2::theme_set(ggplot2::theme_light())
```

```{r}
#Read Data

  Apple_daily <- read_csv("AAPL_D.csv")
  #Apple_monthly <-  read_csv("AAPL_M.csv")
  IBM_daily <-  read_csv("IBM_D.csv")
  #IBM_monthly <-  read_csv("IBM_M.csv") 
  Ralph_daily <-  read_csv("RL_D.csv") 
  #Ralph_monthly <-  read_csv("RL_M.csv") 
  WWE_daily <-  read_csv("WWE_D.csv")
  #WWE_monthly <-  read_csv("WWE_M.csv")
```

```{r}
  colnames(Apple_daily)[6] = "Adj_close"
  #colnames(Apple_monthly)[6] = "Adj_close"
  colnames(IBM_daily)[6] = "Adj_close"
  #colnames(IBM_monthly)[6] = "Adj_close"
  colnames(Ralph_daily)[6] = "Adj_close"
  #colnames(Ralph_monthly)[6] = "Adj_close"
  colnames(WWE_daily)[6] = "Adj_close"
  #colnames(WWE_monthly)[6] = "Adj_close"
```

```{r}
#Add Returns

   Add_return <- function (.data){
  
   .data <- .data %>%
     mutate(
       Adj_close_lagged = lag (Adj_close),
       returns =  Adj_close/Adj_close_lagged
       
       )
      
   }
  
  
   Apple_daily<- Add_return(Apple_daily)
   IBM_daily<- Add_return(IBM_daily)
   Ralph_daily<- Add_return(Ralph_daily)
   WWE_daily<- Add_return(WWE_daily)
   
   
```


```{r}
#Plot CDFs
  
CDF_n_SD1 <- function (.data1,.data2){
  
  n1 <- deparse(substitute(.data1))
  n2 <- deparse(substitute(.data2))
  
  data1 <- data.frame(x=.data1$returns, group = as.character(n1))
  data2 <- data.frame(x=.data2$returns, group = as.character(n2))
  
  df <- rbind(data1,data2)
  
  A <- ggplot(df, aes(x = x, color = group)) + stat_ecdf() + scale_color_manual(values = c("red", "blue"), name = "Legend") +   scale_x_continuous(limits = c(0.95, 1.05), breaks = c(0.95,0.96,0.97,0.98,0.99,1.00,1.01,1.02,1.03,1.04,1.05)) +
  labs(x = "Returns", y = "Cumulative Probability")
  
  ecdf_data_1 <- ecdf(.data1$returns)
  ecdf_data_2 <- ecdf(.data2$returns)
  
  res1 <- paste(as.character(n2) ," doesn't first-order stochastically dominate ", as.character(n1))
  res2 <- paste(n1,"doesn't first-order stochastically dominate", n2)
  
  if (ecdf_data_1(0.95) < ecdf_data_2(0.95)) print (res1) else print (res2)
  if (ecdf_data_1(1.05) < ecdf_data_2(1.05)) print (res1) else print (res2)
  
  return (A)
  
  }

CDF_n_SD1(Apple_daily, IBM_daily)

``` 


```{r}
#Check for second-order Stochastic Dominance


```